name: CI/CD - Discolors

on:
  # Trigger on push to main OR when a version tag is created (e.g., v1.0.1)
  push:
    branches: ['main']
    tags: ['v*']

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    # Add a condition: only run the full release pipeline if a tag is pushed
    if: github.event_name != 'push' || !startsWith(github.ref, 'refs/tags/v')

    steps:
      # -------------------------------
      # Setup & Dependencies
      # -------------------------------
      - name: Checkout repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Run linter and formatter (Check-only)
        run: |
          npm run format -- --check
          npm run lint

      # -------------------------------
      # Build, Package, and Key Management
      # -------------------------------
      - name: Run Vite Production Build
        run: npm run build

      - name: Write private key from Secret
        run: echo "${{ secrets.CRX_PRIVATE_KEY }}" > discolors.pem

      - name: Build CRX and ZIP packages
        run: npm run build-package

      # -------------------------------
      # Versioning (Only runs on 'main' branch push, not on tags)
      # -------------------------------
      - name: Auto-Bump version for main branch (if no tag exists)
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        id: versioning
        run: npx standard-version --skip.tag=true --skip.commit=true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Version for Release Tagging
        id: get_version
        shell: bash
        run: |
          echo "VERSION=$(node -p 'require(\"./package.json\").version')" >> $GITHUB_OUTPUT

      # -------------------------------
      # GitHub Release (Triggered by the created tag)
      # -------------------------------
      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          artifacts: 'build/*.zip,build/*.crx'
          draft: false
          prerelease: false
